### PR TITLE
Improve docs on check

### LINKED ISSUE #180: Update usage docs for Check
Clarify how `check` works when `--hpss=none` on https://e3sm-project.github.io/zstash/_build/html/master/usage.html#check

### PR DESCRIPTION
**Pull request by forsyth2**
Improve docs on `check`. Resolves #180.

### CODE REVIEW

**Comment by forsyth2** [comment]
@chengzhuzhang Does this usage example look good?

**Review by chengzhuzhang — COMMENTED** [review]
Looks good. The new use case doesn't require `--keep` right? Just want to make sure that the tar balls won't be purged.

**Comment by forsyth2** [comment]
> The new use case doesn't require --keep right?

No, when `--hpss=none`, `--keep` is essentially applied automatically.

**Review by chengzhuzhang — COMMENTED** [review]
Thanks for clarifying. In this case, you may want to add this in `--keep` to explain?

**Comment by forsyth2** [comment]
https://e3sm-project.github.io/zstash/_build/html/master/tutorial.html#keep-files does mention "If `--keep` is used with `--hpss=none`, there won’t be a noticeable effect since the latter keeps tar files by default."

I could perhaps add a note at the top of the Usage docs highlighting that though.

**Comment by forsyth2** [comment]
> I could perhaps add a note at the top of the Usage docs highlighting that though.

I added this in #182.

**Pull request merged**
