### PR TITLE
Update sdk

### LINKED ISSUE #196: support newer globus-sdk
The constraint on globus-sdk:
https://github.com/E3SM-Project/zstash/blob/master/conda/meta.yaml#L25
has the side effect of preventing `zstash` and therefore E3SM-Unified from being installed with python 3.10.  Could you see if this constraint is necessary and, if so, what development would be required for zstash to work with the latest globus?

### PR DESCRIPTION
**Pull request by forsyth2**
Update `globus_sdk`. Resolves #196

### CODE REVIEW

**Comment by forsyth2** [comment]
Running `python -m unittest tests/test_*.py` in environment without these changes:
```
.
----------------------------------------------------------------------
Ran 62 tests in 585.516s

OK
```
And with these changes:
```
.
======================================================================
ERROR: testLs (tests.test_globus.TestGlobus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/cscratch1/sd/forsyth/zstash/tests/test_globus.py", line 182, in testLs
    "testLsGlobus", f"globus://{hpss_globus_endpoint}/~/zstash_test/"
  File "/global/cscratch1/sd/forsyth/zstash/tests/test_globus.py", line 159, in helperLsGlobus
    self.preactivate_globus()
  File "/global/cscratch1/sd/forsyth/zstash/tests/test_globus.py", line 62, in preactivate_globus
    native_client.login(no_local_server=True, refresh_tokens=True)
  File "/global/homes/f/forsyth/miniconda3/envs/zstash_issue196/lib/python3.7/site-packages/fair_research_login/client.py", line 159, in login
    **kwargs)
  File "/global/homes/f/forsyth/miniconda3/envs/zstash_issue196/lib/python3.7/site-packages/fair_research_login/client.py", line 198, in get_code
    additional_params=additional_params
TypeError: oauth2_get_authorize_url() got an unexpected keyword argument 'additional_params'

----------------------------------------------------------------------
Ran 62 tests in 526.255s

FAILED (errors=1)
```

**Comment by forsyth2** [comment]
The second commit (based on https://github.com/lukaszlacinski/zstash/commit/13c266029ef41742bb10f19cb6d8e1be99a4de58 from @lukaszlacinski) gets the tests passing again.

**Comment by forsyth2** [comment]
@xylar This closes #196, meaning `zstash` should now support `python 3.10`.

**Comment by xylar** [comment]
That's great!

**Comment by xylar** [comment]
@forsyth2, I have questions about the changes made here.  It should always be that `conda/meta.yaml` and `setup.py` have the same exact constraints on packages.  Otherwise, `pip check` will not pass.  Do you know why stricter (and different) constraints were added to `setup.py` than in `conda/meta.yaml` in this PR?

**Comment by forsyth2** [comment]
>  It should always be that conda/meta.yaml and setup.py have the same exact constraints on packages.

I was unaware of that.

> Do you know why stricter (and different) constraints were added to `setup.py` than in `conda/meta.yaml` in this PR?

No, I can only imagine I was going with the least strict requirements needed for it to work.

**Comment by tomvothecoder** [comment]
> No, I can only imagine I was going with the least strict requirements needed for it to work. @tomvothecoder or @lukaszlacinski might remember why, but I'm not sure.

If I recall correctly,`globus-sdk` v2 and v3 had breaking API changes where modules were renamed and/or moved around. These breaking changes cascaded to thee Python imports in `zstash`. The workaround was to constrain `globus-sdk >=2, <3` in `setup.py` in #188.

I'm not sure of the history of the dependencies since then and why things are constrained differently in `setup.py` and `meta.yaml`. It looks like the `zstash` `conda` package using `meta.yaml` builds fine? If so, maybe aligning the dependencies between both files will work (although we should eventually replace the `pip` build workflow with `conda` in GitHub Actions).

**Comment by xylar** [comment]
Let's settle on the right set of constraints in #250.

**Pull request merged**
