### PR TITLE
Update help text

### LINKED ISSUE #65: Add no-hpss information to zstash -h
`zstash create -h` gives information about options for this command. It should be specified here (and perhaps in other help pages) that `--hpss=none` should be used if you do not have HPSS available.

### LINKED ISSUE #72: zstash ls --help incomplete
Very minor (add to issue #65) but the usage for "zstash ls --help" says

- usage: zstash ls [<args>]

but should say

- usage: zstash ls [<args>] [files]

in line with the "zstash extract help"

(base) -bash-4.1$ zstash version
v0.4.1
(base) -bash-4.1$ zstash ls --help
usage: zstash ls [<args>]

List the files from an existing archive

positional arguments:     < - - - but in what position?
  files

optional arguments:
  -h, --help     show this help message and exit

optional named arguments:
  --hpss HPSS    path to HPSS storage
  -l             show more information for the files
  -v, --verbose  increase output verbosity

### LINKED ISSUE #87: Update help text for create, update, extract
The `--help` text could be improved for `create`, `update`, and `extract`:

Recommendations from @TonyB9000 :

For `create`: `--hpss HPSS        path to HPSS storage` -> `--hpss HPSS        path to HPSS storage, or '--hpss=none' for local archiving.`

For the following 3 cases, “CACHE” is described as “path to store files”, but with --hpss=none, would a better description be “path to local destination archive” or “path to local source archive”?

For Create:  (selected lines of interest only)
```
positional arguments:
  path               root directory to archive
optional named arguments:
  --keep             keep tar files in local cache (default off)
  --cache CACHE      path to store files
```

For Update:  (selected lines of interest only)
```
  --hpss HPSS        path to HPSS storage
  --keep             keep tar files in local cache (default off)
  --cache CACHE      path to store files
```

For Extract:  (selected lines of interest only)
```
optional named arguments:
  --hpss HPSS        path to HPSS storage
  --workers WORKERS  num of multiprocess workers
  --keep             keep tar files in local cache (default off)
  --cache CACHE      path to store files
```

### PR DESCRIPTION
**Pull request by forsyth2**
Update help text. Resolves #87. Resolves #72. Resolves #65.

### CODE REVIEW

**Comment by forsyth2** [comment]
@TonyB9000 This pull request addresses three issues related to your suggestions to improve the help text. Please let me know what you think. Thanks.

**Review by golaz — APPROVED** [review]
Looks good.

**Comment by forsyth2** [comment]
@golaz @TonyB9000 Ok, I think the help text looks good now. Please let me know if you agree. Thanks!

**Review by TonyB9000 — APPROVED** [review]
These changes are perfect - very clear and complete.  Thanks Ryan!

**Pull request merged**
