### PR TITLE
Update docs for v1.1.0

### LINKED ISSUE #142: Finalize docs for v1.1.0
Before releasing v1.1.0 we should make sure the docs look good. 

E.g.:
- Add information on what's new in v1.1.0.
- The tutorial (https://e3sm-project.github.io/zstash/_build/html/master/tutorial.html) should probably mention what `zstash` version it was run with. (We should also delete line with "INFO: You're using the version at").

### PR DESCRIPTION
**Pull request by forsyth2**
Update docs for v1.1.0. Resolves #142

### CODE REVIEW

**Comment by forsyth2** [comment]
@golaz I think this is ready for review. I can't think of anything else the docs need before v1.1.0 is released. #140 was the only feature we added for this release and I updated the docs to explain it. I specifically didn't include docs on the `--no_tars_md5` option since that's really only for developers/debuggers.

**Review by golaz — APPROVED** [review]
The changes are fine. There are a couple of other places where some content could be added:

- Home page: mention that checksums of the tar files are now computed as well on the fly.
- 'Database' page which lists the sql tables.
- 'Usage - List': should we add one example with --tars option?
-

**Comment by forsyth2** [comment]
@golaz Thanks! I added a second commit to address your suggestions. If those look good, I'll squash the commits and merge.

**Comment by golaz** [comment]
Thanks @forsyth2. Go ahead and merge.

**Pull request merged**
