### PR TITLE
License etc

### LINKED ISSUE #89: zstash needs a LICENSE!
I'm pretty sure E3SM would want there to be some sort of LICENSE file.

### PR DESCRIPTION
**Pull request by chengzhuzhang**
Add License, Notice file and modify Readme file following LLNL open source software guideline 
closes #89

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Finally got the IM release code. @forsyth2

**Review by forsyth2 — APPROVED** [review]
I'm not really sure what we're required to have, but these additions seem reasonable to me. Thanks!

**Comment by chengzhuzhang** [comment]
I'm following guild lines here: https://software.llnl.gov/about/licenses/

**Comment by forsyth2** [comment]
> I'm following guild lines here: https://software.llnl.gov/about/licenses/ Please feel free to merge

Sounds good!

**Pull request merged**
